### ISSUE TITLE
dialog ou whiptail?

### ISSUE THREAD

**Issue by ephiguxta** [vcatafesta/sena#2]
O programa tem a opção de criar menu com `dialog` e/ou `whiptail`, o problema é que na função [check_deps](https://github.com/vcatafesta/sena/blob/c3ea4ef77ecbf0c380d79442cffecd711d6a68d7/sena#L444) a forma de se checar exige que se tenha ambos os softwares instalados, temos que modificar a função e permitir que se tenha no mínimo um dos softwares.

**Comment by vcatafesta** [comment]
Valeu Fabio, bem lembrado, vamos remover a dependência do whiptail
